// src/app/may-tinh-PC-day-du/data.ts
import { Product } from "./types"

export const products: Product[] = [
  {
    id: 1,
    type: "gaming",
    brand: "ASUS",
    cpu: "Intel Core i7",
    gpu: "RTX 4070",
    ram: "16GB",
    name: "PC Gaming ASUS RTX 4070",
    price: 35000000,
    shortDesc: "PC gaming ASUS hiệu năng cao, card RTX 4070",
    description: "Hiệu năng cao, chơi game mượt mà",
    images: [
      "https://images.unsplash.com/photo-1612831455542-2d3e2b9c8b91?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 5,
    seller: {
      id: 101,
      name: "Nguyễn Văn A",
      avatar: "https://i.pravatar.cc/150?img=1",
    },
  },
  {
    id: 2,
    type: "office",
    brand: "HP",
    cpu: "Intel Core i5",
    gpu: "Intel UHD",
    ram: "8GB",
    name: "PC Văn phòng HP Core i5",
    price: 12000000,
    shortDesc: "PC văn phòng HP ổn định, tiết kiệm điện",
    description: "Tiết kiệm điện, chạy ổn định",
    images: [
      "https://images.unsplash.com/photo-1587202372775-9899f1f9c3f4?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 12,
    seller: {
      id: 102,
      name: "Trần Thị B",
      avatar: "https://i.pravatar.cc/150?img=2",
    },
  },
  {
    id: 3,
    type: "workstation",
    brand: "Dell",
    cpu: "AMD Ryzen 9",
    gpu: "RTX 3080",
    ram: "32GB",
    name: "Workstation Dell RTX 3080",
    price: 45000000,
    shortDesc: "Workstation Dell mạnh mẽ cho thiết kế 3D",
    description: "Phục vụ dựng phim, thiết kế 3D chuyên nghiệp",
    images: [
      "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 3,
    seller: {
      id: 103,
      name: "Phạm Văn C",
      avatar: "https://i.pravatar.cc/150?img=3",
    },
  },
  {
    id: 4,
    type: "gaming",
    brand: "MSI",
    cpu: "AMD Ryzen 7",
    gpu: "RX 6800 XT",
    ram: "16GB",
    name: "PC Gaming MSI Ryzen 7",
    price: 30000000,
    shortDesc: "PC gaming MSI Ryzen 7, chiến game AAA mượt",
    description: "Chiến game AAA cực mượt",
    images: [
      "https://images.unsplash.com/photo-1612831455702-5b2e9c8f7b91?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 7,
    seller: {
      id: 104,
      name: "Nguyễn Thị D",
      avatar: "https://i.pravatar.cc/150?img=4",
    },
  },
  {
    id: 5,
    type: "mini",
    brand: "Intel NUC",
    cpu: "Intel Core i5",
    gpu: "Intel Iris Xe",
    ram: "16GB",
    name: "Mini PC Intel NUC i5",
    price: 15000000,
    shortDesc: "Mini PC nhỏ gọn, tiết kiệm không gian",
    description: "Phù hợp cho văn phòng và học tập",
    images: [
      "https://images.unsplash.com/photo-1612197528440-9b8a3d2ff3e1?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 10,
    seller: {
      id: 105,
      name: "Lê Văn E",
      avatar: "https://i.pravatar.cc/150?img=5",
    },
  },
  {
    id: 6,
    type: "gaming",
    brand: "Gigabyte",
    cpu: "Intel Core i9",
    gpu: "RTX 4090",
    ram: "64GB",
    name: "PC Gaming Gigabyte RTX 4090",
    price: 90000000,
    shortDesc: "Hiệu năng đỉnh cao với RTX 4090",
    description: "Chiến mọi tựa game 4K siêu mượt",
    images: [
      "https://images.unsplash.com/photo-1612197592222-13a7e7f3a3e2?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 2,
    seller: {
      id: 106,
      name: "Phạm Thị F",
      avatar: "https://i.pravatar.cc/150?img=6",
    },
  },
  {
    id: 7,
    type: "office",
    brand: "Lenovo",
    cpu: "Intel Core i3",
    gpu: "Intel UHD",
    ram: "8GB",
    name: "PC Văn phòng Lenovo Core i3",
    price: 8000000,
    shortDesc: "Giải pháp giá rẻ cho văn phòng",
    description: "Tiết kiệm chi phí, đáp ứng nhu cầu cơ bản",
    images: [
      "https://images.unsplash.com/photo-1601979039764-770d1a5a0a93?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 15,
    seller: {
      id: 107,
      name: "Nguyễn Văn G",
      avatar: "https://i.pravatar.cc/150?img=7",
    },
  },
  {
    id: 8,
    type: "workstation",
    brand: "Apple",
    cpu: "Apple M2 Ultra",
    gpu: "Integrated 60-core GPU",
    ram: "64GB",
    name: "Apple Mac Studio M2 Ultra",
    price: 120000000,
    shortDesc: "Workstation cao cấp của Apple",
    description: "Dành cho thiết kế đồ họa và dựng phim chuyên nghiệp",
    images: [
      "https://images.unsplash.com/photo-1655720087895-f4b4d8a2b47f?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 1,
    seller: {
      id: 108,
      name: "Trần Thị H",
      avatar: "https://i.pravatar.cc/150?img=8",
    },
  },
  {
    id: 9,
    type: "gaming",
    brand: "Acer",
    cpu: "Intel Core i7",
    gpu: "RTX 3060",
    ram: "16GB",
    name: "PC Gaming Acer RTX 3060",
    price: 25000000,
    shortDesc: "Cấu hình tốt cho game thủ tầm trung",
    description: "Đáp ứng tốt nhu cầu gaming 1080p, 2K",
    images: [
      "https://images.unsplash.com/photo-1626908013945-1b57a637fd05?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 8,
    seller: {
      id: 109,
      name: "Đặng Văn I",
      avatar: "https://i.pravatar.cc/150?img=9",
    },
  },
  {
    id: 10,
    type: "mini",
    brand: "ASRock",
    cpu: "AMD Ryzen 5",
    gpu: "Radeon Vega",
    ram: "8GB",
    name: "Mini PC ASRock Ryzen 5",
    price: 11000000,
    shortDesc: "Mini PC tiết kiệm điện năng",
    description: "Gọn nhẹ, phù hợp phòng nhỏ và văn phòng",
    images: [
      "https://images.unsplash.com/photo-1612197598850-39e9eabc75da?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 9,
    seller: {
      id: 110,
      name: "Phan Thị K",
      avatar: "https://i.pravatar.cc/150?img=10",
    },
  },
  {
    id: 11,
    type: "workstation",
    brand: "HP Z",
    cpu: "Intel Xeon",
    gpu: "RTX A6000",
    ram: "128GB",
    name: "Workstation HP Z Xeon",
    price: 150000000,
    shortDesc: "Máy trạm mạnh mẽ cho AI/ML",
    description: "Chạy các mô hình AI, Deep Learning nhanh chóng",
    images: [
      "https://images.unsplash.com/photo-1626898743363-f5aa1db93a12?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 2,
    seller: {
      id: 111,
      name: "Nguyễn Văn L",
      avatar: "https://i.pravatar.cc/150?img=11",
    },
  },
  {
    id: 12,
    type: "gaming",
    brand: "Razer",
    cpu: "Intel Core i9",
    gpu: "RTX 4080",
    ram: "32GB",
    name: "PC Gaming Razer RTX 4080",
    price: 75000000,
    shortDesc: "Gaming PC phong cách Razer RGB",
    description: "Chiến mọi game ở cấu hình cao nhất",
    images: [
      "https://images.unsplash.com/photo-1626908043179-6fd8c3b6a3a3?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 4,
    seller: {
      id: 112,
      name: "Trần Thị M",
      avatar: "https://i.pravatar.cc/150?img=12",
    },
  },
  {
    id: 13,
    type: "office",
    brand: "Dell Optiplex",
    cpu: "Intel Core i5",
    gpu: "Intel UHD",
    ram: "8GB",
    name: "Dell Optiplex Office PC",
    price: 10000000,
    shortDesc: "PC văn phòng Dell bền bỉ",
    description: "Đáp ứng nhu cầu văn phòng cơ bản",
    images: [
      "https://images.unsplash.com/photo-1601979039764-770d1a5a0a93?auto=format&fit=crop&w=800&q=80",
    ],
    stock: 20,
    seller: {
      id: 113,
      name: "Vũ Văn N",
      avatar: "https://i.pravatar.cc/150?img=13",
    },
  },
]
